// Generated by scripts/extract-data.ts. Defaults are intentionally fail-closed.
export const priceSyncGeneratedAt = "2026-08-17T10:39:05.432Z";
export const priceFreshAsins: ReadonlySet<string> = new Set([]);

export function isProductPriceFresh(asin?: string): boolean {
  return Boolean(asin && priceFreshAsins.has(asin));
}
