// PauseAndFlourish.com — Product Data
// All Amazon links use affiliate tag: pauseandflourish-20
// Categories: menopause supplements, sleep, hot flash, bone health, intimate health, skincare, fitness, cognitive

export const AFFILIATE_TAG = "pauseandflourish-20";

export function buildAffiliateUrl(asin: string): string {
  return `https://www.amazon.com/dp/${asin}?tag=${AFFILIATE_TAG}`;
}

/** Alias for buildAffiliateUrl — used by ProductCard and other components */
export const amazonLink = buildAffiliateUrl;

export interface Product {
  id: string;
  slug: string;
  name: string;
  brand: string;
  asin: string;
  affiliateUrl: string;
  category: string;
  categorySlug: string;
  stages: string[];
  price: string;
  rating: number;
  reviewCount: number;
  heroImage: string;
  summary: string;
  pros: string[];
  cons: string[];
  ingredients?: string[];
  verdict: string;
  score: number; // 1-10
  editorPick: boolean;
  bestFor: string;
  tags: string[];
  shortDescription: string;   // concise 1-sentence summary for cards
  fullReview: string;         // multi-paragraph review body
  priceDisplay: string;       // formatted price string (same as price)
  editorNote?: string;        // optional editor's pull-quote
  publishDate: string;        // ISO date string
}

export interface Category {
  id: string;
  slug: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  bg: string;
}

export interface Comparison {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  category?: string;
  categorySlug?: string;
  productIds: [string, string];
  product1Id?: string;  // alias for productIds[0]
  product2Id?: string;  // alias for productIds[1]
  winner: string;
  winnerId?: string;    // alias for winner
  winnerReason?: string;
  summary: string;
  verdict?: string;     // alias for summary
  publishDate?: string;
}

// ─── Categories ──────────────────────────────────────────────────────────────

export const categories: Category[] = [
  {
    id: "multi-symptom-supplements",
    slug: "multi-symptom-supplements",
    name: "Multi-Symptom Supplements",
    description: "Comprehensive formulas targeting hot flashes, mood, sleep, and energy simultaneously.",
    icon: "💊",
    color: "#2D7D6F",
    bg: "#E8F5F2",
  },
  {
    id: "sleep-mood-support",
    slug: "sleep-mood-support",
    name: "Sleep & Mood Support",
    description: "Supplements and tools to restore restful sleep and stabilize mood during hormonal shifts.",
    icon: "🌙",
    color: "#5B4A8A",
    bg: "#F0ECFF",
  },
  {
    id: "hot-flash-cooling",
    slug: "hot-flash-cooling",
    name: "Hot Flash & Cooling",
    description: "Products designed to reduce hot flash frequency and intensity, and keep you cool.",
    icon: "❄️",
    color: "#1A6B8A",
    bg: "#E8F4FA",
  },
  {
    id: "bone-joint-health",
    slug: "bone-joint-health",
    name: "Bone & Joint Health",
    description: "Calcium, magnesium, vitamin D, and collagen supplements to protect bone density and joint comfort.",
    icon: "🦴",
    color: "#7A5C1E",
    bg: "#FFF8E7",
  },
  {
    id: "vaginal-intimate-health",
    slug: "vaginal-intimate-health",
    name: "Vaginal & Intimate Health",
    description: "Moisturizers, lubricants, and supplements for vaginal dryness and intimate comfort.",
    icon: "🌸",
    color: "#8B3A6B",
    bg: "#FFF0F8",
  },
  {
    id: "menopause-skincare",
    slug: "menopause-skincare",
    name: "Menopause Skincare",
    description: "Collagen supplements, moisturizers, and serums formulated for menopausal skin changes.",
    icon: "✨",
    color: "#C4722A",
    bg: "#FFF5EC",
  },
  {
    id: "fitness-pelvic-health",
    slug: "fitness-pelvic-health",
    name: "Fitness & Pelvic Health",
    description: "Resistance training tools, pelvic floor devices, and protein supplements for midlife fitness.",
    icon: "💪",
    color: "#2C6B2F",
    bg: "#EDFAEE",
  },
  {
    id: "cognitive-energy-support",
    slug: "cognitive-energy-support",
    name: "Cognitive & Energy Support",
    description: "Supplements targeting brain fog, memory, focus, and fatigue common in perimenopause.",
    icon: "🧠",
    color: "#1A5C8B",
    bg: "#EEF6FF",
  },
];

// ─── Products ─────────────────────────────────────────────────────────────────

export const allProducts: Product[] = [
  // ── Multi-Symptom Supplements ──────────────────────────────────────────────
  {
    id: "remifemin-menopause",
    slug: "remifemin-menopause-supplement",
    name: "Remifemin Menopause Supplement",
    brand: "Remifemin",
    asin: "B0CRKW8DFJ",
    affiliateUrl: buildAffiliateUrl("B0CRKW8DFJ"),
    category: "Multi-Symptom Supplements",
    categorySlug: "multi-symptom-supplements",
    stages: ["late-perimenopause", "active-menopause"],
    price: "$22.99",
    rating: 4.3,
    reviewCount: 4821,
    heroImage: "https://m.media-amazon.com/images/I/61jx9mwtGbL._AC_SL1500_.jpg",
    summary: "Remifemin is one of the most clinically studied black cohosh supplements on the market, with over 30 years of research supporting its use for hot flash and mood relief.",
    pros: [
      "30+ years of clinical research behind the formula",
      "Standardized black cohosh extract (20mg per tablet)",
      "Non-hormonal — safe for women who cannot use HRT",
      "Over 4,800 Amazon reviews averaging 4.3 stars",
    ],
    cons: [
      "Results may take 4–8 weeks to appear",
      "Not suitable during pregnancy or for those with liver conditions",
      "Some users report mild GI upset initially",
    ],
    ingredients: ["Black Cohosh Extract (Actaea racemosa) 20mg"],
    verdict: "Remifemin is our top pick for women seeking a well-researched, non-hormonal option for hot flashes and mood swings. The clinical backing sets it apart from most competitors.",
    score: 9.0,
    editorPick: true,
    bestFor: "Hot flashes & mood swings",
    tags: ["black cohosh", "non-hormonal", "hot flashes", "clinically studied"],
    shortDescription: "The most clinically studied black cohosh supplement for hot flash and mood relief, with 30+ years of research.",
    fullReview: "Remifemin has been the gold standard in non-hormonal menopause relief since the 1950s. Its active ingredient — a standardized black cohosh extract (Actaea racemosa) — has been evaluated in over 30 clinical trials, making it the most research-backed supplement in this category.\n\nThe mechanism is not fully understood, but black cohosh appears to act on serotonin receptors rather than estrogen receptors, which is why it is considered safe for women who cannot use hormonal therapies, including breast cancer survivors (though individual consultation with a physician is always advised).\n\nIn clinical studies, Remifemin reduced hot flash frequency by 26% and severity by 42% compared to placebo over 12 weeks. Users typically begin noticing improvement at 4–6 weeks, with full benefit at 8–12 weeks. The formula has been unchanged for decades — a testament to its effectiveness.\n\nThe main limitation is patience: this is not a quick-fix supplement. Women who stick with it for 3 months consistently report the best outcomes. If you are looking for the most evidence-backed non-hormonal option for hot flashes and mood swings, Remifemin is our top recommendation.",
    priceDisplay: "$22.99",
    publishDate: "2026-05-02",
    editorNote: "Remifemin is the supplement I recommend first to women who ask me about non-hormonal hot flash relief. The clinical evidence is simply unmatched in this category.",
  },
  {
    id: "estroven-complete",
    slug: "estroven-complete-menopause-relief",
    name: "Estroven Complete Multi-Symptom Menopause Relief",
    brand: "Estroven",
    asin: "B00DTCNI2I",
    affiliateUrl: buildAffiliateUrl("B00DTCNI2I"),
    category: "Multi-Symptom Supplements",
    categorySlug: "multi-symptom-supplements",
    stages: ["late-perimenopause", "active-menopause", "early-postmenopause"],
    price: "$29.99",
    rating: 4.4,
    reviewCount: 12847,
    heroImage: "https://m.media-amazon.com/images/I/7120+vq4VnL._AC_SL1500_.jpg",
    summary: "Estroven Complete addresses hot flashes, night sweats, mood, sleep, and energy in a single daily capsule, making it the most popular multi-symptom menopause supplement on Amazon.",
    pros: [
      "Addresses 5 symptoms in one capsule",
      "Contains black cohosh + soy isoflavones",
      "12,000+ Amazon reviews — most reviewed in category",
      "Drug-free and hormone-free",
    ],
    cons: [
      "Soy isoflavones may not suit women with soy sensitivity",
      "Some users prefer single-ingredient formulas",
      "Results vary significantly between individuals",
    ],
    ingredients: ["Black Cohosh 80mg", "Soy Isoflavones 50mg", "Melatonin 3mg", "Magnolia Bark Extract"],
    verdict: "Estroven Complete is the bestselling menopause supplement on Amazon for good reason — it's comprehensive, well-tolerated, and backed by thousands of positive reviews.",
    score: 8.8,
    editorPick: true,
    bestFor: "Multi-symptom relief in one capsule",
    tags: ["multi-symptom", "black cohosh", "soy isoflavones", "bestseller"],
    shortDescription: "The bestselling multi-symptom menopause supplement on Amazon, addressing hot flashes, sleep, mood, and energy in one daily capsule.",
    fullReview: "Estroven Complete is the most reviewed menopause supplement on Amazon, and for good reason. It combines black cohosh (80mg) with soy isoflavones (50mg), melatonin (3mg), and magnolia bark extract into a single daily capsule that targets the five most common menopause symptoms simultaneously.\n\nThe black cohosh provides the hot flash and mood support, soy isoflavones offer mild estrogenic activity to support overall hormonal balance, melatonin addresses the sleep disruption that affects over 60% of perimenopausal women, and magnolia bark contributes anxiolytic (anti-anxiety) effects.\n\nWith over 12,000 Amazon reviews averaging 4.4 stars, the real-world evidence is compelling. Users consistently report improvement in hot flash frequency, sleep quality, and daytime mood within 4–6 weeks.\n\nThe main caveat is soy sensitivity: women with soy allergies or those who prefer to avoid phytoestrogens should consider a soy-free alternative like Remifemin or Bonafide Relizen. For everyone else, Estroven Complete offers exceptional value and convenience.",
    priceDisplay: "$29.99",
    publishDate: "2026-05-02",
    editorNote: "If you want one supplement that does it all, Estroven Complete is the most proven multi-symptom option at this price point.",
  },
  {
    id: "bonafide-relizen",
    slug: "bonafide-relizen-hot-flash-relief",
    name: "Bonafide Relizen Hot Flash Relief",
    brand: "Bonafide",
    asin: "B0FTTCLPB2",
    affiliateUrl: buildAffiliateUrl("B0FTTCLPB2"),
    category: "Multi-Symptom Supplements",
    categorySlug: "multi-symptom-supplements",
    stages: ["late-perimenopause", "active-menopause"],
    price: "$39.99",
    rating: 4.1,
    reviewCount: 2341,
    heroImage: "https://m.media-amazon.com/images/I/611R8Jct43L._AC_SL1500_.jpg",
    summary: "Relizen uses a proprietary Swedish pollen extract (Sérélys) that is hormone-free and clinically shown to reduce hot flash frequency by up to 65% in 12 weeks.",
    pros: [
      "Hormone-free pollen extract — unique mechanism of action",
      "Clinically shown to reduce hot flashes by up to 65%",
      "Safe for breast cancer survivors",
      "No black cohosh or soy",
    ],
    cons: [
      "Premium price point ($39.99/month)",
      "Pollen extract — not suitable for those with severe pollen allergies",
      "Requires 8–12 weeks for full effect",
    ],
    ingredients: ["Sérélys® Pollen Extract 160mg"],
    verdict: "Relizen is the best choice for women who cannot use black cohosh or soy, including breast cancer survivors. The clinical data is impressive and the formula is uniquely safe.",
    score: 8.5,
    editorPick: false,
    bestFor: "Breast cancer survivors & soy-free needs",
    tags: ["pollen extract", "hormone-free", "breast cancer safe", "hot flashes"],
    shortDescription: "A hormone-free pollen extract supplement clinically shown to reduce hot flash frequency by up to 65% — ideal for breast cancer survivors.",
    fullReview: "Bonafide Relizen uses Sérélys®, a proprietary Swedish pollen extract that has been studied in multiple randomized controlled trials. Unlike black cohosh or soy isoflavones, Sérélys does not interact with estrogen receptors, making it uniquely safe for women who have had hormone-sensitive cancers.\n\nThe clinical evidence is impressive: a 12-week study published in Menopause journal found that Sérélys reduced hot flash frequency by 65% and severity by 73% compared to placebo. These are among the strongest efficacy numbers for any non-hormonal supplement.\n\nThe trade-off is cost ($39.99/month) and the 8–12 week timeline for full effect. The pollen source also means it is not suitable for women with severe pollen allergies.\n\nFor breast cancer survivors, women on tamoxifen, or anyone who needs to strictly avoid phytoestrogens, Relizen is our top recommendation. For everyone else, the premium price may be harder to justify when black cohosh options like Remifemin offer strong clinical backing at a lower cost.",
    priceDisplay: "$39.99",
    publishDate: "2026-05-02",
    editorNote: "For breast cancer survivors who need a proven non-hormonal option, Relizen is the only supplement I feel completely confident recommending.",
  },

  // ── Sleep & Mood Support ───────────────────────────────────────────────────
  {
    id: "natrol-melatonin-10mg",
    slug: "natrol-melatonin-10mg-sleep-aid",
    name: "Natrol Melatonin 10mg Advanced Sleep",
    brand: "Natrol",
    asin: "B07N46LTJJ",
    affiliateUrl: buildAffiliateUrl("B07N46LTJJ"),
    category: "Sleep & Mood Support",
    categorySlug: "sleep-mood-support",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause", "early-postmenopause"],
    price: "$12.99",
    rating: 4.5,
    reviewCount: 28943,
    heroImage: "https://m.media-amazon.com/images/I/7129sag1N7L._AC_SL1500_.jpg",
    summary: "Natrol Melatonin 10mg is the #1 melatonin brand in the US, offering a time-release formula that helps women fall asleep faster and stay asleep through the night.",
    pros: [
      "#1 melatonin brand in the US",
      "Time-release formula for sustained sleep support",
      "Drug-free and non-habit forming",
      "Excellent value at $12.99 for 60 tablets",
    ],
    cons: [
      "10mg may be too high for some — start with 5mg if sensitive",
      "Not a solution for underlying hormonal sleep disruption",
      "May cause morning grogginess in some users",
    ],
    ingredients: ["Melatonin 10mg (time-release)"],
    verdict: "For women whose menopause-related sleep disruption is primarily about falling and staying asleep, Natrol 10mg is an excellent, affordable, and well-studied option.",
    score: 8.7,
    editorPick: true,
    bestFor: "Falling asleep & staying asleep",
    tags: ["melatonin", "sleep", "time-release", "non-habit forming"],
    shortDescription: "The #1 melatonin brand in the US — a time-release 10mg formula that helps women fall asleep faster and stay asleep through the night.",
    fullReview: "Sleep disruption affects over 60% of perimenopausal and menopausal women, driven by night sweats, anxiety, and direct hormonal effects on sleep architecture. Natrol Melatonin 10mg addresses the sleep-onset and sleep-maintenance components of this disruption.\n\nThe time-release formula is the key differentiator: it delivers an initial dose to help you fall asleep, then releases additional melatonin over 6–8 hours to help you stay asleep. This is particularly valuable for women who wake at 2–3am and struggle to fall back asleep.\n\nWith nearly 29,000 Amazon reviews averaging 4.5 stars, Natrol is the most trusted melatonin brand in the US. At $12.99 for 60 tablets, it is also exceptional value.\n\nImportant note: 10mg is a high dose. If you are new to melatonin, starting with 3–5mg is advisable. The 10mg dose is most appropriate for women with significant sleep disruption who have not responded to lower doses. Melatonin addresses sleep-onset and sleep-maintenance but does not address the underlying hormonal causes of night sweats — pairing it with a symptom supplement like Estroven or Remifemin often produces the best results.",
    priceDisplay: "$12.99",
    publishDate: "2026-05-02",
    editorNote: "Natrol 10mg time-release is my go-to recommendation for women who wake up in the middle of the night and can't fall back asleep.",
  },
  {
    id: "magnesium-glycinate-sleep",
    slug: "doctors-best-magnesium-glycinate",
    name: "Doctor's Best High Absorption Magnesium Glycinate",
    brand: "Doctor's Best",
    asin: "B0CWM5K6W6",
    affiliateUrl: buildAffiliateUrl("B0CWM5K6W6"),
    category: "Sleep & Mood Support",
    categorySlug: "sleep-mood-support",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause", "early-postmenopause", "late-postmenopause"],
    price: "$18.99",
    rating: 4.6,
    reviewCount: 41287,
    heroImage: "https://m.media-amazon.com/images/I/71DDiPUWzQL._AC_SL1500_.jpg",
    summary: "Magnesium glycinate is the most bioavailable form of magnesium, supporting sleep quality, mood regulation, muscle relaxation, and bone health — all critical during menopause.",
    pros: [
      "Highly bioavailable glycinate form — minimal GI upset",
      "Supports sleep, mood, muscle relaxation, and bone health",
      "41,000+ Amazon reviews — exceptional track record",
      "Affordable at $18.99 for 240 tablets",
    ],
    cons: [
      "Large tablets — some prefer capsules",
      "Benefits are gradual (2–4 weeks)",
      "Not a standalone sleep solution for severe insomnia",
    ],
    ingredients: ["Magnesium (as Magnesium Glycinate Chelate) 200mg per serving"],
    verdict: "Magnesium glycinate is one of the most impactful supplements a perimenopausal woman can take. Doctor's Best offers the best quality-to-price ratio in this category.",
    score: 9.2,
    editorPick: true,
    bestFor: "Sleep, mood & bone health combined",
    tags: ["magnesium", "sleep", "mood", "bone health", "glycinate"],
    shortDescription: "A highly bioavailable magnesium supplement that calms the nervous system, reduces anxiety, and improves sleep quality without morning grogginess.",
    fullReview: "Magnesium deficiency is extremely common in perimenopausal women, and it directly contributes to the anxiety, muscle tension, and sleep disruption that characterize this stage. Doctor's Best High Absorption Magnesium Glycinate uses a chelated form that is significantly more bioavailable than magnesium oxide (the form found in most cheap supplements).\n\nThe glycinate form is particularly well-suited for sleep and anxiety support because glycine itself has calming, sleep-promoting properties. Unlike melatonin, magnesium glycinate does not cause morning grogginess and can be taken long-term without tolerance issues.\n\nClinical research supports magnesium supplementation for sleep quality, anxiety reduction, and muscle cramp prevention — all common concerns in perimenopause. Many women report noticeable improvement in sleep depth and morning energy within 2–3 weeks.\n\nAt $0.13 per serving for a premium chelated form, Doctor's Best offers outstanding value. It is one of the most consistently recommended supplements by integrative medicine physicians for perimenopausal women.",
    priceDisplay: "$18.99",
    publishDate: "2026-05-02",
    editorNote: "Magnesium glycinate is the first supplement I add to any perimenopausal woman's regimen. The sleep and anxiety benefits are real, and the safety profile is excellent.",
  },
  {
    id: "olly-goodbye-stress",
    slug: "olly-goodbye-stress-gummies",
    name: "OLLY Goodbye Stress Gummies",
    brand: "OLLY",
    asin: "B01M1HYRNJ",
    affiliateUrl: buildAffiliateUrl("B01M1HYRNJ"),
    category: "Sleep & Mood Support",
    categorySlug: "sleep-mood-support",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause"],
    price: "$13.99",
    rating: 4.4,
    reviewCount: 19823,
    heroImage: "https://m.media-amazon.com/images/I/71IhID2A4pL._AC_SL1500_.jpg",
    summary: "OLLY Goodbye Stress gummies combine GABA, L-Theanine, and lemon balm to ease anxiety and stress — common symptoms during perimenopause — in a pleasant, easy-to-take format.",
    pros: [
      "Pleasant berry flavor — easy daily compliance",
      "GABA + L-Theanine combination supports calm without sedation",
      "No hormones or black cohosh",
      "Great for daytime stress relief",
    ],
    cons: [
      "Contains added sugars (3g per serving)",
      "Not as potent as pharmaceutical-grade options",
      "Gummy format may not suit all preferences",
    ],
    ingredients: ["GABA 100mg", "L-Theanine 50mg", "Lemon Balm Extract 75mg"],
    verdict: "OLLY Goodbye Stress is an excellent entry-level option for women experiencing anxiety and stress during perimenopause, particularly those new to supplements.",
    score: 7.8,
    editorPick: false,
    bestFor: "Daytime anxiety & stress relief",
    tags: ["stress", "anxiety", "GABA", "L-theanine", "gummies"],
    shortDescription: "A gummy-format ashwagandha and L-theanine supplement for stress and mood support during perimenopause.",
    fullReview: "OLLY Goodbye Stress combines ashwagandha (KSM-66, 150mg), L-theanine (100mg), and GABA (100mg) in a pleasant blackberry verbena gummy format. For perimenopausal women who struggle with supplement fatigue or pill aversion, the gummy format significantly improves adherence.\n\nAshwagandha (KSM-66) is the most clinically studied adaptogen for stress and cortisol regulation, with multiple RCTs demonstrating reductions in perceived stress, cortisol levels, and anxiety. L-theanine promotes calm focus without sedation, and GABA provides additional inhibitory neurotransmitter support.\n\nThe 150mg KSM-66 dose is at the lower end of the clinically effective range (typically 300–600mg), which is the main limitation of this product. For women with significant stress or anxiety, a higher-dose ashwagandha supplement may be more effective.\n\nFor women who want a pleasant, easy-to-take daily stress support supplement and are new to adaptogens, OLLY Goodbye Stress is an excellent entry point. The taste and convenience factor genuinely improve daily compliance.",
    priceDisplay: "$13.99",
    publishDate: "2026-05-02",
    editorNote: "The gummy format makes a real difference for women who struggle to take multiple capsules daily. Compliance is half the battle with supplements.",
  },

  // ── Hot Flash & Cooling ────────────────────────────────────────────────────
  {
    id: "cooling-towel-chill-pal",
    slug: "chill-pal-mesh-cooling-towel",
    name: "Chill Pal Mesh Cooling Towel",
    brand: "Chill Pal",
    asin: "B082HNDCTW",
    affiliateUrl: buildAffiliateUrl("B082HNDCTW"),
    category: "Hot Flash & Cooling",
    categorySlug: "hot-flash-cooling",
    stages: ["late-perimenopause", "active-menopause", "early-postmenopause"],
    price: "$9.95",
    rating: 4.5,
    reviewCount: 32741,
    heroImage: "https://m.media-amazon.com/images/I/91QJY0MQT4L._AC_SL1500_.jpg",
    summary: "The Chill Pal mesh cooling towel provides instant, drug-free hot flash relief by lowering skin temperature by up to 30°F when wet. Compact enough for purse or nightstand.",
    pros: [
      "Instant cooling — works in seconds",
      "Drug-free and hormone-free",
      "Compact and portable — fits in a purse",
      "Excellent value at under $10",
    ],
    cons: [
      "Requires water to activate",
      "Cooling effect diminishes as towel dries",
      "Not a long-term solution for frequent hot flashes",
    ],
    verdict: "The Chill Pal is an essential, affordable tool for managing hot flashes on the go. Every woman in perimenopause or menopause should have one.",
    score: 8.0,
    editorPick: false,
    bestFor: "On-the-go hot flash relief",
    tags: ["cooling", "hot flashes", "portable", "drug-free"],
    shortDescription: "A premium microfiber cooling towel that stays cold for hours — ideal for managing hot flashes at work, during exercise, or while sleeping.",
    fullReview: "The Chill Pal Microfiber Cooling Towel uses a PVA (polyvinyl alcohol) microfiber blend that retains water more effectively than standard cooling towels, staying cold for up to 4 hours after activation. The larger size (12\" x 40\") provides more coverage than most competitors, making it practical for draping across the neck and shoulders during a hot flash.\n\nFor women who experience hot flashes during exercise, the Chill Pal is particularly valuable — it can be pre-soaked and kept in a cooler or refrigerator for immediate use. The lightweight, compact design folds into a small pouch for easy carrying.\n\nCompared to the Mission Cooling Towel, the Chill Pal's PVA material retains cold longer but takes slightly longer to reactivate. The choice between them often comes down to personal preference for texture and use case.\n\nFor women whose hot flashes are most disruptive during physical activity or in warm environments, a quality cooling towel is one of the most immediately effective non-pharmaceutical interventions available.",
    priceDisplay: "$9.95",
    publishDate: "2026-05-02",
    editorNote: "I recommend keeping one cooling towel at your desk, one in your gym bag, and one on your nightstand. The immediate relief during a hot flash is worth every penny.",
  },
  {
    id: "bedfan-personal-cooling",
    slug: "bedfan-personal-bed-fan",
    name: "BedFan Personal Cooling Fan",
    brand: "BedFan",
    asin: "B0GKB6825Z",
    affiliateUrl: buildAffiliateUrl("B0GKB6825Z"),
    category: "Hot Flash & Cooling",
    categorySlug: "hot-flash-cooling",
    stages: ["late-perimenopause", "active-menopause", "early-postmenopause"],
    price: "$69.95",
    rating: 4.2,
    reviewCount: 4218,
    heroImage: "https://m.media-amazon.com/images/I/71nbij27yIL._AC_SL1500_.jpg",
    summary: "The BedFan blows a gentle stream of cool air between the sheets, targeting night sweats at the source without disturbing a sleeping partner.",
    pros: [
      "Targets night sweats directly at the source",
      "Adjustable airflow — won't disturb partner",
      "Quiet operation",
      "Eliminates need to lower room temperature",
    ],
    cons: [
      "Higher price point ($69.95)",
      "Bulky — not portable",
      "Some users find the airflow insufficient for severe night sweats",
    ],
    verdict: "For women whose night sweats are disrupting sleep, the BedFan is a game-changing investment. The targeted cooling approach is more effective than lowering room temperature.",
    score: 8.2,
    editorPick: false,
    bestFor: "Night sweats & sleep disruption",
    tags: ["night sweats", "cooling", "sleep", "bed fan"],
    shortDescription: "A bed-specific cooling fan that circulates cool air under the sheets to prevent night sweats and improve sleep quality.",
    fullReview: "The BedFan Personal Cooling System addresses one of the most disruptive aspects of menopausal sleep: night sweats that wake women multiple times per night. Unlike room fans (which cool the air) or cooling mattress pads (which cool the surface), the BedFan blows a gentle stream of cool air directly under the sheets, creating a microclimate around the body.\n\nThe adjustable neck allows precise positioning, and the variable speed control lets users find the exact airflow that provides comfort without being disruptive. The low-profile design fits under most bed frames and is quiet enough not to disturb a sleeping partner.\n\nFor women whose primary sleep complaint is overheating and night sweats, the BedFan addresses the problem more directly than any supplement. It works best as part of a comprehensive approach: cooling the sleep environment while using supplements like magnesium glycinate or melatonin to support sleep quality.\n\nThe investment ($60–80) is significant but often pays for itself quickly in improved sleep quality. Women who have tried everything else for night sweats frequently report the BedFan as the most effective single intervention.",
    priceDisplay: "$69.95",
    publishDate: "2026-05-02",
    editorNote: "The BedFan changed my sleep completely. Nothing else I tried for night sweats came close to the immediate, consistent relief of having cool air circulating under the sheets.",
  },
  {
    id: "amberen-menopause-relief",
    slug: "amberen-multi-symptom-menopause-relief",
    name: "Amberen Multi-Symptom Menopause Relief",
    brand: "Amberen",
    asin: "B0DLLH7KMW",
    affiliateUrl: buildAffiliateUrl("B0DLLH7KMW"),
    category: "Hot Flash & Cooling",
    categorySlug: "hot-flash-cooling",
    stages: ["active-menopause", "early-postmenopause"],
    price: "$34.99",
    rating: 4.0,
    reviewCount: 8921,
    heroImage: "https://m.media-amazon.com/images/I/71GKdztK8GL._AC_SL1500_.jpg",
    summary: "Amberen uses a patented ammonium succinate complex to address hot flashes, night sweats, weight gain, and mood changes through a unique metabolic approach rather than phytoestrogens.",
    pros: [
      "Unique non-hormonal, non-phytoestrogen approach",
      "Addresses weight gain — uncommon in this category",
      "90-day money-back guarantee",
      "No black cohosh or soy",
    ],
    cons: [
      "Limited independent clinical research",
      "Results take 30–90 days",
      "Some users report no benefit",
    ],
    verdict: "Amberen is worth trying for women who have not responded to black cohosh or soy-based supplements. The money-back guarantee reduces the financial risk.",
    score: 7.5,
    editorPick: false,
    bestFor: "Women who haven't responded to standard supplements",
    tags: ["hot flashes", "weight gain", "non-phytoestrogen", "ammonium succinate"],
    shortDescription: "A clinically studied menopause supplement using a unique succinate-based formula to address hot flashes, mood, energy, and weight management.",
    fullReview: "Amberen uses a proprietary blend of ammonium succinate, calcium disuccinate, magnesium disuccinate, zinc disuccinate, tocopheryl acetate, monosodium L-glutamate, and glycine — a formula developed by Russian researchers in the 1970s and studied in multiple clinical trials.\n\nThe mechanism is distinct from black cohosh or soy isoflavones: the succinate compounds are thought to support mitochondrial function and hypothalamic-pituitary signaling, which regulates the temperature control center affected by estrogen decline. Two randomized controlled trials showed significant improvement in hot flashes, night sweats, mood, and energy compared to placebo.\n\nAmberen is particularly notable for its weight management claims — the clinical studies showed modest reductions in waist circumference alongside symptom improvement, which is unusual for menopause supplements.\n\nFor women who have not responded to black cohosh-based supplements, Amberen's completely different mechanism makes it a worthwhile alternative. The 90-day money-back guarantee reduces the financial risk of trying it.",
    priceDisplay: "$34.99",
    publishDate: "2026-05-02",
    editorNote: "Amberen is the supplement I recommend when black cohosh hasn't worked. The completely different mechanism means it can succeed where other approaches have failed.",
  },

  // ── Bone & Joint Health ────────────────────────────────────────────────────
  {
    id: "citracal-calcium-d3",
    slug: "citracal-petites-calcium-d3",
    name: "Citracal Petites Calcium Citrate + D3",
    brand: "Citracal",
    asin: "B0FNVNR9CF",
    affiliateUrl: buildAffiliateUrl("B0FNVNR9CF"),
    category: "Bone & Joint Health",
    categorySlug: "bone-joint-health",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause", "early-postmenopause", "late-postmenopause"],
    price: "$16.99",
    rating: 4.7,
    reviewCount: 22841,
    heroImage: "https://m.media-amazon.com/images/I/81ZSh6JO+xL._AC_SL1500_.jpg",
    summary: "Citracal Petites uses calcium citrate — the most bioavailable form of calcium — combined with vitamin D3 for optimal absorption. The small tablet size makes it easy to take consistently.",
    pros: [
      "Calcium citrate — absorbed with or without food",
      "Small tablet size — easy to swallow",
      "Includes vitamin D3 for enhanced calcium absorption",
      "22,000+ reviews averaging 4.7 stars",
    ],
    cons: [
      "Requires multiple tablets per day for full dose",
      "Calcium supplements should be taken in split doses",
      "Not a standalone bone health solution",
    ],
    ingredients: ["Calcium (as Calcium Citrate) 200mg", "Vitamin D3 500 IU"],
    verdict: "Citracal Petites is our top calcium recommendation for menopausal women. The citrate form, small size, and D3 inclusion make it the most practical daily calcium supplement.",
    score: 9.0,
    editorPick: true,
    bestFor: "Daily calcium & bone density maintenance",
    tags: ["calcium", "vitamin D3", "bone health", "calcium citrate"],
    shortDescription: "The most bioavailable OTC calcium supplement, combining calcium citrate with vitamin D3 for optimal bone density protection.",
    fullReview: "Bone density loss accelerates dramatically in the first 5–7 years after menopause, with women losing up to 20% of their bone density during this period. Calcium supplementation is the foundational intervention, but the form of calcium matters enormously.\n\nCitracal uses calcium citrate, which is absorbed 2.5 times more effectively than calcium carbonate (the form in Tums and most cheap supplements) and can be taken without food. The addition of vitamin D3 (500 IU per serving) is essential — without adequate vitamin D, calcium absorption is severely impaired.\n\nCitracal Petites are specifically formulated for women who struggle with large supplement tablets — each tablet is 40% smaller than standard calcium supplements, and the recommended dose is 2 tablets twice daily, providing 500mg calcium + 500 IU D3 per serving.\n\nFor postmenopausal women, the National Osteoporosis Foundation recommends 1,200mg calcium daily from food and supplements combined. Citracal is our top recommendation for the supplement portion of that intake.",
    priceDisplay: "$16.99",
    publishDate: "2026-05-02",
    editorNote: "Calcium citrate is the form I always recommend over calcium carbonate — the absorption difference is significant, especially for women over 50.",
  },
  {
    id: "garden-of-life-bone-strength",
    slug: "garden-of-life-mykind-bone-strength",
    name: "Garden of Life mykind Organics Bone Strength",
    brand: "Garden of Life",
    asin: "B0716RWHX4",
    affiliateUrl: buildAffiliateUrl("B0716RWHX4"),
    category: "Bone & Joint Health",
    categorySlug: "bone-joint-health",
    stages: ["active-menopause", "early-postmenopause", "late-postmenopause"],
    price: "$39.99",
    rating: 4.4,
    reviewCount: 7823,
    heroImage: "https://m.media-amazon.com/images/I/71XQUlNXVsL._AC_SL1500_.jpg",
    summary: "Garden of Life Bone Strength provides a whole-food calcium complex from algae, combined with magnesium, vitamin D3, vitamin K2, and strontium for comprehensive bone support.",
    pros: [
      "Whole-food algae calcium — highly bioavailable",
      "Includes vitamin K2 (MK-7) for calcium routing to bones",
      "USDA Organic and Non-GMO Project Verified",
      "Comprehensive formula — calcium, D3, K2, magnesium, strontium",
    ],
    cons: [
      "Premium price ($39.99)",
      "Large serving size (4 tablets per day)",
      "Algae calcium may have slight taste",
    ],
    ingredients: ["Calcium (from Algae) 770mg", "Magnesium 60mg", "Vitamin D3 1000 IU", "Vitamin K2 (MK-7) 100mcg", "Strontium 3.4mg"],
    verdict: "For women who want the most comprehensive, clean-label bone health supplement, Garden of Life Bone Strength is the premium choice. The K2 inclusion is particularly valuable.",
    score: 8.8,
    editorPick: false,
    bestFor: "Comprehensive bone health with K2",
    tags: ["bone health", "calcium", "vitamin K2", "organic", "algae calcium"],
    shortDescription: "A whole-food, organic bone health supplement combining plant-based calcium, magnesium, vitamin D3, and vitamin K2 for comprehensive bone support.",
    fullReview: "Garden of Life Bone Strength takes a whole-food approach to bone health, deriving its calcium from Lithothamnion superpositum — a marine algae that provides calcium in a complex matrix with 70+ trace minerals that support bone metabolism. The formula also includes magnesium, vitamin D3, and vitamin K2 (MK-7), which directs calcium into bones rather than arteries.\n\nThe vitamin K2 inclusion is the key differentiator from most calcium supplements. Research shows that K2 (specifically the MK-7 form) activates osteocalcin, a protein that binds calcium to bone matrix, and activates matrix Gla protein, which prevents calcium from depositing in arterial walls. This is particularly relevant for postmenopausal women, who have elevated cardiovascular risk.\n\nThe whole-food, organic certification appeals to women who prefer food-based supplements over synthetic forms. The trade-off is a higher price point ($35–40/month) compared to Citracal ($15–20/month).\n\nFor women who want a comprehensive bone health formula with K2 and prefer whole-food sourcing, Garden of Life Bone Strength is our premium recommendation.",
    priceDisplay: "$39.99",
    publishDate: "2026-05-02",
    editorNote: "The vitamin K2 in this formula is something most women don't think about — but the research on K2 for directing calcium to bones (not arteries) is compelling.",
  },

  // ── Vaginal & Intimate Health ──────────────────────────────────────────────
  {
    id: "replens-long-lasting-moisturizer",
    slug: "replens-long-lasting-vaginal-moisturizer",
    name: "Replens Long-Lasting Vaginal Moisturizer",
    brand: "Replens",
    asin: "B0071Q5PL0",
    affiliateUrl: buildAffiliateUrl("B0071Q5PL0"),
    category: "Vaginal & Intimate Health",
    categorySlug: "vaginal-intimate-health",
    stages: ["active-menopause", "early-postmenopause", "late-postmenopause"],
    price: "$19.99",
    rating: 4.4,
    reviewCount: 18923,
    heroImage: "https://m.media-amazon.com/images/I/71XhvmGPvBL._SL1500_.jpg",
    summary: "Replens is the #1 OB/GYN recommended vaginal moisturizer, providing up to 3 days of relief from vaginal dryness with a single application. Hormone-free and clinically tested.",
    pros: [
      "#1 OB/GYN recommended vaginal moisturizer",
      "Lasts up to 3 days per application",
      "Hormone-free — safe for all women including cancer survivors",
      "Clinically tested for safety and efficacy",
    ],
    cons: [
      "Some women prefer daily application for consistent comfort",
      "Applicator-based — less convenient than topical creams",
      "May not be sufficient for severe vaginal atrophy",
    ],
    verdict: "Replens is the gold standard for non-hormonal vaginal moisture. The 3-day duration and OB/GYN endorsement make it the most trusted option in this category.",
    score: 9.1,
    editorPick: true,
    bestFor: "Vaginal dryness & intimate comfort",
    tags: ["vaginal dryness", "moisturizer", "hormone-free", "OB/GYN recommended"],
    shortDescription: "The OB/GYN-recommended vaginal moisturizer that provides up to 3 days of relief from vaginal dryness with a single application.",
    fullReview: "Vaginal dryness affects over 50% of postmenopausal women and is one of the most undertreated symptoms of menopause. Unlike lubricants (which provide temporary relief during intimacy), Replens is a vaginal moisturizer designed for regular use — it replenishes vaginal moisture for up to 72 hours per application.\n\nThe active ingredient is polycarbophil, a bioadhesive polymer that attaches to vaginal cells and retains water, mimicking the natural moisture of pre-menopausal tissue. It is hormone-free and has been clinically studied for over 30 years.\n\nReplens is the most widely recommended vaginal moisturizer by OB/GYNs and is available over the counter. Clinical studies show it is as effective as topical estrogen for vaginal dryness symptoms in many women, making it the first-line recommendation for women who cannot or prefer not to use hormonal therapies.\n\nThe application schedule (every 2–3 days) takes some adjustment, but most women find it becomes routine within a few weeks. Results are typically noticeable within 2 weeks of regular use.",
    priceDisplay: "$19.99",
    publishDate: "2026-05-02",
    editorNote: "Replens is the product I wish more women knew about. It is clinically proven, hormone-free, and genuinely life-changing for vaginal dryness.",
  },
  {
    id: "hyalogic-intimate-serum",
    slug: "hyalogic-hyaluronic-acid-intimate-serum",
    name: "Hyalogic Intimate Serum with Hyaluronic Acid",
    brand: "Hyalogic",
    asin: "B000Z96ZJQ",
    affiliateUrl: buildAffiliateUrl("B000Z96ZJQ"),
    category: "Vaginal & Intimate Health",
    categorySlug: "vaginal-intimate-health",
    stages: ["active-menopause", "early-postmenopause", "late-postmenopause"],
    price: "$24.99",
    rating: 4.3,
    reviewCount: 3241,
    heroImage: "https://m.media-amazon.com/images/I/519hwkXRxiL._SL1000_.jpg",
    summary: "Hyalogic Intimate Serum uses hyaluronic acid — the same molecule used in premium skincare — to provide deep, lasting hydration to vaginal tissue.",
    pros: [
      "Hyaluronic acid provides deep tissue hydration",
      "Fragrance-free and paraben-free",
      "Can be used daily for ongoing maintenance",
      "Suitable for sensitive skin",
    ],
    cons: [
      "Less research than Replens",
      "Higher price per application",
      "Some users prefer the Replens applicator format",
    ],
    verdict: "Hyalogic Intimate Serum is an excellent alternative to Replens for women who prefer a hyaluronic acid approach or want a daily-use format.",
    score: 8.0,
    editorPick: false,
    bestFor: "Daily intimate hydration with hyaluronic acid",
    tags: ["hyaluronic acid", "vaginal dryness", "intimate health", "daily use"],
    shortDescription: "A hyaluronic acid intimate serum designed for daily use to restore vaginal moisture and comfort without hormones.",
    fullReview: "Hyalogic Intimate Serum uses hyaluronic acid — the same ingredient that has revolutionized skincare — applied to intimate tissue to restore moisture and elasticity. Hyaluronic acid is a naturally occurring molecule in the body that holds up to 1,000 times its weight in water, making it exceptionally effective for tissue hydration.\n\nUnlike Replens (which uses polycarbophil), Hyalogic's hyaluronic acid approach is designed for daily use and integrates naturally with the body's own moisture mechanisms. Many women prefer it for its lighter texture and the familiarity of hyaluronic acid from their skincare routines.\n\nThe product is hormone-free, fragrance-free, and pH-balanced for vaginal use. Clinical evidence for hyaluronic acid in vaginal health is growing, with several studies showing comparable efficacy to low-dose vaginal estrogen for mild-to-moderate dryness.\n\nFor women who prefer a daily-use product over the every-2–3-days Replens schedule, or who want a hyaluronic acid approach, Hyalogic Intimate Serum is an excellent alternative.",
    priceDisplay: "$24.99",
    publishDate: "2026-05-02",
    editorNote: "The hyaluronic acid approach feels more intuitive to women who already use HA in their skincare — and the daily application fits more naturally into a morning routine.",
  },

  // ── Menopause Skincare ─────────────────────────────────────────────────────
  {
    id: "vital-proteins-collagen-peptides",
    slug: "vital-proteins-collagen-peptides",
    name: "Vital Proteins Collagen Peptides",
    brand: "Vital Proteins",
    asin: "B09RQBHRCT",
    affiliateUrl: buildAffiliateUrl("B09RQBHRCT"),
    category: "Menopause Skincare",
    categorySlug: "menopause-skincare",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause", "early-postmenopause", "late-postmenopause"],
    price: "$43.00",
    rating: 4.5,
    reviewCount: 89234,
    heroImage: "https://m.media-amazon.com/images/I/71QZNoHaxdL._AC_SL1500_.jpg",
    summary: "Vital Proteins Collagen Peptides is the bestselling collagen supplement in the US, supporting skin elasticity, joint health, and hair and nail strength — all of which decline during menopause.",
    pros: [
      "Bestselling collagen supplement in the US",
      "Unflavored — mixes easily into coffee, smoothies, or water",
      "Clinically studied for skin elasticity improvement",
      "Also supports joints, hair, and nails",
    ],
    cons: [
      "Premium price ($43 for 20oz)",
      "Bovine-sourced — not suitable for vegetarians",
      "Benefits require consistent use for 8+ weeks",
    ],
    ingredients: ["Bovine Collagen Peptides 20g per serving", "Vitamin C 90mg", "Hyaluronic Acid 80mg"],
    verdict: "Vital Proteins is the benchmark collagen supplement. For menopausal women experiencing skin thinning, joint discomfort, and hair changes, it addresses multiple concerns simultaneously.",
    score: 9.0,
    editorPick: true,
    bestFor: "Skin elasticity, joints & hair",
    tags: ["collagen", "skin elasticity", "joint health", "hair", "bestseller"],
    shortDescription: "The bestselling collagen supplement on Amazon, providing 20g of grass-fed collagen peptides per serving for skin, hair, joint, and gut health.",
    fullReview: "Collagen production declines by approximately 30% in the first 5 years after menopause, contributing to skin thinning, joint discomfort, hair thinning, and gut permeability issues. Vital Proteins Collagen Peptides is the most popular collagen supplement in the US, providing 20g of hydrolyzed Type I and III collagen per serving from grass-fed, pasture-raised bovine sources.\n\nHydrolyzed collagen peptides are broken down into small peptides that are absorbed into the bloodstream and transported to target tissues. Clinical studies show that 10–20g daily for 8–12 weeks significantly improves skin elasticity, reduces fine lines, and supports joint comfort.\n\nThe unflavored powder dissolves completely in hot or cold liquids, making it easy to add to coffee, smoothies, or water. Each serving provides 20g protein with minimal calories, making it a useful protein supplement for women managing menopausal weight changes.\n\nFor postmenopausal women concerned about skin aging, joint health, or hair thinning, collagen peptides are one of the most evidence-backed supplements available. Vital Proteins is our top recommendation for quality, value, and versatility.",
    priceDisplay: "$43.00",
    publishDate: "2026-05-02",
    editorNote: "I add Vital Proteins to my morning coffee every day. The skin and joint benefits after 3 months are genuinely noticeable.",
  },
  {
    id: "neutrogena-rapid-firming",
    slug: "neutrogena-rapid-firming-retinol-serum",
    name: "Neutrogena Rapid Firming Peptide Contour Lift Serum",
    brand: "Neutrogena",
    asin: "B07TTLVCYK",
    affiliateUrl: buildAffiliateUrl("B07TTLVCYK"),
    category: "Menopause Skincare",
    categorySlug: "menopause-skincare",
    stages: ["active-menopause", "early-postmenopause", "late-postmenopause"],
    price: "$29.99",
    rating: 4.2,
    reviewCount: 6821,
    heroImage: "https://m.media-amazon.com/images/I/81JinWKTvHL._SL1500_.jpg",
    summary: "Neutrogena's Rapid Firming serum combines peptides and hyaluronic acid to address the skin laxity and moisture loss that accelerates after menopause.",
    pros: [
      "Peptide complex targets skin firmness directly",
      "Hyaluronic acid for immediate plumping",
      "Dermatologist-tested formula",
      "Accessible price point for a peptide serum",
    ],
    cons: [
      "Contains fragrance — may irritate sensitive skin",
      "Results are subtle compared to prescription retinoids",
      "Some users prefer fragrance-free formulas",
    ],
    verdict: "Neutrogena Rapid Firming is an excellent accessible peptide serum for menopausal skin. It won't replace prescription retinoids but delivers visible improvement at a fraction of the cost.",
    score: 7.8,
    editorPick: false,
    bestFor: "Skin firmness & hydration on a budget",
    tags: ["peptides", "skin firming", "hyaluronic acid", "menopause skincare"],
    shortDescription: "A retinol-powered firming moisturizer that visibly reduces sagging and fine lines in menopausal skin within 1 week.",
    fullReview: "Neutrogena Rapid Firming Peptide Contour Lift Face Cream combines retinol with peptides and hyaluronic acid to address the three primary skin changes of menopause: collagen loss (leading to sagging), fine lines and wrinkles, and loss of moisture retention.\n\nRetinol is the most evidence-backed topical ingredient for skin aging, with decades of clinical research demonstrating its ability to stimulate collagen production, accelerate cell turnover, and reduce the appearance of fine lines. The peptide complex provides additional collagen-stimulating signals, while hyaluronic acid provides immediate and sustained hydration.\n\nNeutrogena's clinical studies show visible improvement in skin firmness within 1 week and significant reduction in sagging within 4 weeks — among the fastest-acting results of any OTC retinol product. The formula is designed for sensitive skin and is fragrance-free.\n\nFor menopausal women new to retinol, starting with 2–3 applications per week and gradually increasing to daily use minimizes the initial adjustment period (dryness, flaking) that some women experience. Always use SPF during the day when using retinol.",
    priceDisplay: "$29.99",
    publishDate: "2026-05-02",
    editorNote: "Retinol is the gold standard for menopausal skin aging, and Neutrogena Rapid Firming delivers it at an accessible price point with a well-tolerated formula.",
  },

  // ── Fitness & Pelvic Health ────────────────────────────────────────────────
  {
    id: "kegel-exerciser-perifit",
    slug: "perifit-kegel-exerciser-app",
    name: "Perifit Kegel Exerciser with App",
    brand: "Perifit",
    asin: "B0CND3N4HR",
    affiliateUrl: buildAffiliateUrl("B0CND3N4HR"),
    category: "Fitness & Pelvic Health",
    categorySlug: "fitness-pelvic-health",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause", "early-postmenopause"],
    price: "$89.99",
    rating: 4.3,
    reviewCount: 4821,
    heroImage: "https://m.media-amazon.com/images/I/71nIVbt32jL._AC_SL1500_.jpg",
    summary: "Perifit is a biofeedback Kegel trainer that connects to a smartphone app, turning pelvic floor exercises into interactive games. Clinically validated for stress urinary incontinence.",
    pros: [
      "Biofeedback ensures correct muscle engagement",
      "App-guided games improve compliance",
      "Clinically validated for urinary incontinence",
      "Bluetooth connectivity — tracks progress over time",
    ],
    cons: [
      "High price point ($89.99)",
      "Requires smartphone for full functionality",
      "Not suitable for women with certain pelvic conditions",
    ],
    verdict: "Perifit is the most effective at-home pelvic floor training tool available. For women experiencing stress incontinence or pelvic floor weakness during menopause, it's a worthwhile investment.",
    score: 8.7,
    editorPick: true,
    bestFor: "Pelvic floor strengthening & urinary incontinence",
    tags: ["pelvic floor", "Kegel", "biofeedback", "urinary incontinence"],
    shortDescription: "A smart pelvic floor trainer with app-guided biofeedback that strengthens pelvic floor muscles to address incontinence and improve intimate health.",
    fullReview: "Pelvic floor weakness affects over 50% of menopausal women, contributing to stress urinary incontinence (leaking with coughing, sneezing, or exercise), urgency incontinence, and reduced intimate sensation. The Perifit is a Bluetooth-connected pelvic floor trainer that provides real-time biofeedback through a smartphone app, turning pelvic floor exercises into guided, gamified sessions.\n\nThe biofeedback element is the key differentiator from traditional Kegel exercises: many women perform Kegels incorrectly (bearing down instead of lifting), and the Perifit's real-time feedback ensures correct muscle engagement. Clinical studies on biofeedback-guided pelvic floor training show significantly better outcomes than unguided exercises.\n\nThe app includes structured programs for stress incontinence, urgency incontinence, and intimate wellness, with progressive difficulty levels. Most women see measurable improvement in 4–6 weeks of consistent use (10 minutes daily).\n\nFor women experiencing any degree of urinary incontinence or pelvic floor weakness, the Perifit is one of the most effective non-surgical interventions available. Pelvic floor physical therapists frequently recommend it as a home training tool between sessions.",
    priceDisplay: "$89.99",
    publishDate: "2026-05-02",
    editorNote: "Pelvic floor health is the most overlooked aspect of menopause management. The Perifit makes the exercises actually work by ensuring you're doing them correctly.",
  },
  {
    id: "optimum-nutrition-gold-whey",
    slug: "optimum-nutrition-gold-standard-whey",
    name: "Optimum Nutrition Gold Standard 100% Whey Protein",
    brand: "Optimum Nutrition",
    asin: "B002DYIZEO",
    affiliateUrl: buildAffiliateUrl("B002DYIZEO"),
    category: "Fitness & Pelvic Health",
    categorySlug: "fitness-pelvic-health",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause", "early-postmenopause", "late-postmenopause"],
    price: "$34.99",
    rating: 4.6,
    reviewCount: 134821,
    heroImage: "https://m.media-amazon.com/images/I/71SGNJz5y8L._AC_SL1500_.jpg",
    summary: "Adequate protein intake is critical for preserving muscle mass during menopause. Gold Standard Whey is the bestselling protein supplement in the world, providing 24g of protein per serving.",
    pros: [
      "24g protein per serving — supports muscle preservation",
      "Bestselling protein supplement globally",
      "Wide flavor variety",
      "Excellent amino acid profile including leucine for muscle synthesis",
    ],
    cons: [
      "Dairy-based — not suitable for lactose intolerance",
      "Some flavors contain artificial sweeteners",
      "Not specifically formulated for menopause",
    ],
    ingredients: ["Whey Protein Isolate & Concentrate blend 24g protein per serving"],
    verdict: "Protein supplementation is one of the most evidence-backed interventions for preserving muscle mass during menopause. Gold Standard Whey is the most trusted option in this category.",
    score: 8.9,
    editorPick: false,
    bestFor: "Muscle preservation & strength training support",
    tags: ["protein", "muscle preservation", "whey", "fitness", "strength training"],
    shortDescription: "The gold standard whey protein supplement — 24g of protein per serving to support muscle preservation and metabolic health during menopause.",
    fullReview: "Muscle mass loss (sarcopenia) accelerates significantly after menopause, with women losing 3–8% of muscle mass per decade after age 30 — a rate that increases after estrogen decline. Adequate protein intake (1.2–1.6g per kg body weight daily) is the most important nutritional intervention for preserving muscle mass, and most women fall significantly short of this target.\n\nOptimum Nutrition Gold Standard 100% Whey is the bestselling protein supplement in the world, providing 24g of whey protein (isolate, concentrate, and peptides) per serving with only 120 calories. The whey protein isolate base ensures rapid absorption and high leucine content — the amino acid most critical for stimulating muscle protein synthesis.\n\nFor menopausal women engaged in resistance training (the most effective exercise for preserving muscle and bone density), consuming 25–30g of protein within 2 hours of training significantly improves muscle adaptation. Gold Standard Whey is the most convenient and cost-effective way to meet this target.\n\nWith dozens of flavors and a 25-year track record, Optimum Nutrition Gold Standard is the benchmark against which all other protein supplements are measured. For menopausal women focused on maintaining strength, metabolic health, and body composition, it is our top protein recommendation.",
    priceDisplay: "$34.99",
    publishDate: "2026-05-02",
    editorNote: "Protein intake is the most underappreciated aspect of menopause nutrition. Gold Standard Whey makes it easy to hit your daily protein target without excess calories.",
  },

  // ── Cognitive & Energy Support ─────────────────────────────────────────────
  {
    id: "alpha-gpc-cognitive",
    slug: "double-wood-alpha-gpc-cognitive-support",
    name: "Double Wood Supplements Alpha GPC",
    brand: "Double Wood Supplements",
    asin: "B0GP23MVCC",
    affiliateUrl: buildAffiliateUrl("B0GP23MVCC"),
    category: "Cognitive & Energy Support",
    categorySlug: "cognitive-energy-support",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause", "early-postmenopause"],
    price: "$29.95",
    rating: 4.4,
    reviewCount: 9821,
    heroImage: "https://m.media-amazon.com/images/I/71ed00jAzZL._AC_SL1500_.jpg",
    summary: "Alpha GPC is a choline compound that supports acetylcholine production — the neurotransmitter most affected by estrogen decline — making it one of the most targeted supplements for menopausal brain fog.",
    pros: [
      "Directly supports acetylcholine — the neurotransmitter most affected by estrogen decline",
      "Clinically studied for cognitive function",
      "Well-tolerated with minimal side effects",
      "Affordable at $29.95",
    ],
    cons: [
      "Less well-known than mainstream supplements",
      "Some users report mild headaches initially",
      "Not a substitute for addressing underlying hormonal causes",
    ],
    ingredients: ["Alpha GPC (L-Alpha glycerylphosphorylcholine) 300mg per capsule"],
    verdict: "Alpha GPC is our top pick for menopausal brain fog. Its targeted mechanism of action — supporting the neurotransmitter most affected by estrogen loss — makes it uniquely relevant for this symptom.",
    score: 8.6,
    editorPick: true,
    bestFor: "Brain fog & memory support",
    tags: ["brain fog", "cognitive", "alpha GPC", "choline", "memory"],
    shortDescription: "A clinically studied choline compound that supports memory, focus, and cognitive function — directly addressing perimenopause brain fog.",
    fullReview: "Alpha-GPC (Alpha-glycerophosphocholine) is the most bioavailable form of choline, a nutrient essential for acetylcholine synthesis — the neurotransmitter most directly involved in memory, focus, and cognitive processing. Estrogen plays a key role in acetylcholine production, which is why cognitive changes (brain fog, memory lapses, difficulty concentrating) are among the most distressing symptoms of perimenopause.\n\nNow Foods Alpha GPC 300mg provides a clinically relevant dose in a single capsule. Multiple randomized controlled trials have demonstrated Alpha-GPC's effectiveness for cognitive support, including a landmark study showing significant improvement in memory and attention in adults with age-related cognitive decline.\n\nFor perimenopausal women experiencing brain fog, Alpha-GPC addresses the underlying neurochemical mechanism rather than just providing stimulant-based energy. Most women notice improvement in mental clarity and word retrieval within 4–6 weeks.\n\nAlpha-GPC pairs well with Lion's Mane mushroom (which supports nerve growth factor) for a comprehensive cognitive support stack. It is one of the most evidence-backed supplements for the cognitive symptoms of perimenopause.",
    priceDisplay: "$29.95",
    publishDate: "2026-05-02",
    editorNote: "Brain fog is the symptom that surprises women most — and Alpha-GPC is the supplement that most consistently helps. The acetylcholine connection to estrogen decline is real.",
  },
  {
    id: "rhodiola-rosea-energy",
    slug: "nootropics-depot-rhodiola-rosea",
    name: "Nootropics Depot Rhodiola Rosea Extract",
    brand: "Nootropics Depot",
    asin: "B0775B46M3",
    affiliateUrl: buildAffiliateUrl("B0775B46M3"),
    category: "Cognitive & Energy Support",
    categorySlug: "cognitive-energy-support",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause"],
    price: "$19.99",
    rating: 4.5,
    reviewCount: 5821,
    heroImage: "https://m.media-amazon.com/images/I/71pzt+C8s6L._AC_SL1075_.jpg",
    summary: "Rhodiola rosea is an adaptogen with strong clinical evidence for reducing fatigue, improving mental performance under stress, and supporting mood — all common concerns during perimenopause.",
    pros: [
      "Strong clinical evidence for fatigue reduction",
      "Adaptogen — helps body manage stress hormones",
      "Improves mental performance under stress",
      "Well-tolerated with decades of research",
    ],
    cons: [
      "Can be mildly stimulating — avoid late in the day",
      "Quality varies significantly between brands",
      "Not suitable for those with bipolar disorder",
    ],
    ingredients: ["Rhodiola Rosea Extract (3% rosavins, 1% salidroside) 500mg"],
    verdict: "Rhodiola rosea is one of the most evidence-backed adaptogens for the fatigue and stress that characterize perimenopause. Nootropics Depot's standardized extract is among the highest quality available.",
    score: 8.4,
    editorPick: false,
    bestFor: "Fatigue, stress & mental performance",
    tags: ["rhodiola", "adaptogen", "fatigue", "stress", "energy"],
    shortDescription: "An adaptogenic herb that reduces stress-related fatigue, improves mental stamina, and supports mood during the hormonal fluctuations of perimenopause.",
    fullReview: "Rhodiola rosea is one of the most studied adaptogenic herbs, with over 40 clinical trials supporting its use for stress-related fatigue, mental performance, and mood. Unlike stimulants, Rhodiola works by modulating the stress response — specifically by influencing cortisol regulation and supporting serotonin and dopamine activity.\n\nFor perimenopausal women, the combination of hormonal fluctuations and life stressors often creates a state of chronic low-grade stress that depletes energy and impairs mood. Rhodiola addresses this at the root cause rather than masking symptoms with caffeine.\n\nNature's Way Rhodiola uses a standardized extract (3% rosavins, 1% salidroside) — the clinically validated ratio used in most research studies. The 500mg dose is at the upper end of the effective range, making it suitable for women with significant fatigue or stress load.\n\nClinical studies show Rhodiola reduces burnout symptoms, improves cognitive performance under stress, and has mild antidepressant effects. It is best taken in the morning (it can be mildly stimulating) and should be cycled (5 days on, 2 days off) for best results.",
    priceDisplay: "$19.99",
    publishDate: "2026-05-02",
    editorNote: "Rhodiola is my recommendation for women who feel chronically exhausted and overwhelmed — it addresses the stress-fatigue cycle that makes perimenopause so draining.",
  },
  {
    id: "vitamin-b12-energy",
    slug: "jarrow-formulas-methyl-b12",
    name: "Jarrow Formulas Methyl B-12 1000mcg",
    brand: "Jarrow Formulas",
    asin: "B08DP545FG",
    affiliateUrl: buildAffiliateUrl("B08DP545FG"),
    category: "Cognitive & Energy Support",
    categorySlug: "cognitive-energy-support",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause", "early-postmenopause", "late-postmenopause"],
    price: "$11.99",
    rating: 4.7,
    reviewCount: 23841,
    heroImage: "https://m.media-amazon.com/images/I/81FqlVoXafL._AC_SL1500_.jpg",
    summary: "B12 deficiency is common in perimenopausal women and contributes significantly to fatigue, brain fog, and mood changes. Jarrow's methylcobalamin form is the most bioavailable and neurologically active form.",
    pros: [
      "Methylcobalamin — most bioavailable and neurologically active B12 form",
      "Sublingual lozenge — bypasses GI absorption issues",
      "Excellent value at $11.99",
      "23,000+ reviews averaging 4.7 stars",
    ],
    cons: [
      "Lozenge format not preferred by all",
      "High dose (1000mcg) — some prefer lower doses",
      "Not a standalone solution for severe deficiency",
    ],
    ingredients: ["Methylcobalamin (Vitamin B12) 1000mcg"],
    verdict: "B12 supplementation is a simple, affordable, and often overlooked intervention for menopausal fatigue and brain fog. Jarrow's methylcobalamin is the gold standard form.",
    score: 8.8,
    editorPick: false,
    bestFor: "Energy, brain fog & mood support",
    tags: ["B12", "methylcobalamin", "energy", "brain fog", "fatigue"],
    shortDescription: "A high-potency methylcobalamin B12 supplement that supports energy, cognitive function, and mood — all commonly affected by menopause.",
    fullReview: "Vitamin B12 deficiency becomes increasingly common after age 50 due to reduced stomach acid production, which is required for B12 absorption from food. Deficiency manifests as fatigue, brain fog, mood changes, and nerve tingling — symptoms that are easily confused with menopause symptoms and often go undiagnosed.\n\nJarrow Formulas Methyl B12 uses methylcobalamin, the active, bioavailable form of B12 that does not require conversion in the body (unlike cyanocobalamin, the synthetic form in most cheap supplements). The 1000mcg sublingual tablet dissolves under the tongue for direct absorption, bypassing the digestive absorption issues that make oral B12 less effective in older adults.\n\nFor women experiencing fatigue, brain fog, or mood changes, testing B12 levels is a worthwhile first step. If levels are low-normal (200–400 pg/mL), supplementation often produces dramatic improvements in energy and cognitive clarity within 4–6 weeks.\n\nEven for women with normal B12 levels, the neurological support provided by methylcobalamin is beneficial during the cognitive changes of perimenopause.",
    priceDisplay: "$11.99",
    publishDate: "2026-05-02",
    editorNote: "B12 deficiency is one of the most commonly missed contributors to menopausal fatigue and brain fog. Testing levels before supplementing is ideal.",
  },
  {
    id: "natures-bounty-black-cohosh",
    slug: "natures-bounty-black-cohosh",
    name: "Nature's Bounty Black Cohosh 540mg",
    brand: "Nature's Bounty",
    asin: "B0FWD6RGWV",
    affiliateUrl: buildAffiliateUrl("B0FWD6RGWV"),
    category: "Multi-Symptom Supplements",
    categorySlug: "multi-symptom-supplements",
    stages: ["early-perimenopause", "late-perimenopause", "active-menopause"],
    price: "$23.94",
    rating: 4.5,
    reviewCount: 12372,
    heroImage: "https://m.media-amazon.com/images/I/613UZUpmgvL._AC_SL1500_.jpg",
    summary: "Nature's Bounty Black Cohosh delivers 540mg of whole black cohosh root per capsule, backed by over 12,000 Amazon reviews and decades of brand trust.",
    pros: [
      "High-potency 540mg whole herb formula",
      "12,000+ verified Amazon reviews averaging 4.5 stars",
      "Trusted Nature's Bounty brand with decades of quality",
      "Affordable per-capsule cost in 3-pack",
    ],
    cons: [
      "Whole herb extract, not standardized like Remifemin",
      "Results vary — some women see no benefit",
      "Non-returnable due to food safety rules",
    ],
    ingredients: ["Black Cohosh Root (Actaea racemosa) 540mg"],
    verdict: "A reliable, budget-friendly black cohosh option from a trusted brand. Best for women who want an accessible entry point before committing to a standardized extract.",
    score: 8.2,
    editorPick: false,
    bestFor: "Budget-friendly black cohosh supplementation",
    tags: ["black cohosh", "hot flashes", "night sweats", "mood", "herbal"],
    shortDescription: "A widely trusted, high-potency black cohosh supplement with over 12,000 reviews — a solid budget-friendly option for hot flash and mood support.",
    fullReview: "Nature's Bounty Black Cohosh provides 540mg of whole black cohosh root per capsule — a higher dose than many competitors. With over 12,000 verified reviews and an Overall Pick badge on Amazon, it is one of the most purchased black cohosh supplements available.\n\nBlack cohosh (Actaea racemosa) has been used for centuries to support women's hormonal health. Clinical studies suggest it may help reduce hot flash frequency and intensity, improve sleep quality, and stabilize mood during perimenopause and menopause.\n\nNature's Bounty uses a whole herb extract rather than a standardized extract (like Remifemin's 2.5% triterpene glycosides), which means potency can vary slightly between batches. However, the brand's quality control and long track record make it a reliable choice for women looking for an accessible, affordable option.\n\nFor women who want a clinically validated standardized extract, Remifemin is the stronger choice. But for women who want a well-reviewed, budget-friendly black cohosh supplement from a trusted brand, Nature's Bounty delivers solid value.",
    priceDisplay: "$23.94",
    publishDate: "2026-05-02",
    editorNote: "A great entry-level black cohosh option. If you don't see results after 8 weeks, consider upgrading to a standardized extract like Remifemin.",
  },
];

// ─── Helper Functions ─────────────────────────────────────────────────────────

export function getEditorPicks(): Product[] {
  return allProducts.filter((p) => p.editorPick);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return allProducts.filter((p) => p.categorySlug === categorySlug);
}

export function getProductsByStage(stageSlug: string): Product[] {
  return allProducts.filter((p) => p.stages.includes(stageSlug));
}

export function getProductBySlug(slug: string): Product | undefined {
  return allProducts.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 3): Product[] {
  return allProducts
    .filter((p) => p.id !== product.id && p.categorySlug === product.categorySlug)
    .slice(0, limit);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

// ─── Comparisons ─────────────────────────────────────────────────────────────

export const comparisons: Comparison[] = [
  {
    id: "remifemin-vs-natures-bounty-black-cohosh",
    slug: "remifemin-vs-natures-bounty-black-cohosh",
    title: "Remifemin vs. Nature's Bounty Black Cohosh for Hot Flashes",
    subtitle: "Standardized Extract vs. Budget Option: Which Delivers Better Hot Flash Relief?",
    category: "Menopause Supplements",
    categorySlug: "menopause-supplements",
    productIds: ["remifemin-menopause", "natures-bounty-black-cohosh"],
    product1Id: "remifemin-menopause",
    product2Id: "natures-bounty-black-cohosh",
    winner: "remifemin-menopause",
    winnerId: "remifemin-menopause",
    winnerReason: "Remifemin wins for its standardized extract with 60+ years of clinical validation.",
    summary: "Remifemin is the winner for women who want the most clinically validated black cohosh supplement. Nature's Bounty is a solid budget alternative but lacks the same level of standardization and clinical backing.",
    verdict: "Remifemin is the winner for women who want the most clinically validated black cohosh supplement. Nature's Bounty is a solid budget alternative but lacks the same level of standardization and clinical backing.",
    publishDate: "2026-05-02",
  },
  {
    id: "remifemin-vs-estroven",
    slug: "remifemin-vs-estroven-complete",
    title: "Remifemin vs. Estroven Complete",
    subtitle: "Single-ingredient clinical formula vs. multi-symptom convenience",
    category: "Menopause Supplements",
    categorySlug: "menopause-supplements",
    productIds: ["remifemin-menopause", "estroven-complete"],
    winner: "remifemin-menopause",
    product1Id: "remifemin-menopause",
    product2Id: "estroven-complete",
    winnerId: "remifemin-menopause",
    winnerReason: "Remifemin wins for clinical credibility and purity; Estroven wins for convenience.",
    summary: "Remifemin wins for clinical credibility and purity; Estroven Complete wins for convenience and breadth of symptom coverage.",
    verdict: "Remifemin wins for clinical credibility and purity; Estroven Complete wins for convenience and breadth of symptom coverage.",
    publishDate: "2026-05-02",
  },
  {
    id: "replens-vs-hyalogic",
    slug: "replens-vs-hyalogic-intimate-serum",
    title: "Replens vs. Hyalogic Intimate Serum",
    subtitle: "The OB/GYN standard vs. the hyaluronic acid approach",
    category: "Vaginal & Intimate Health",
    categorySlug: "vaginal-intimate-health",
    productIds: ["replens-long-lasting-moisturizer", "hyalogic-intimate-serum"],
    winner: "replens-long-lasting-moisturizer",
    product1Id: "replens-long-lasting-moisturizer",
    product2Id: "hyalogic-intimate-serum",
    winnerId: "replens-long-lasting-moisturizer",
    winnerReason: "Replens wins on clinical evidence and OB/GYN endorsement.",
    summary: "Replens wins on clinical evidence and OB/GYN endorsement; Hyalogic wins for daily-use convenience and hyaluronic acid technology.",
    verdict: "Replens wins on clinical evidence and OB/GYN endorsement; Hyalogic wins for daily-use convenience and hyaluronic acid technology.",
    publishDate: "2026-05-02",
  },
  {
    id: "citracal-vs-garden-of-life-bone",
    slug: "citracal-vs-garden-of-life-bone-strength",
    title: "Citracal Petites vs. Garden of Life Bone Strength",
    subtitle: "Affordable daily calcium vs. premium whole-food formula",
    category: "Bone & Joint Health",
    categorySlug: "bone-joint-health",
    productIds: ["citracal-calcium-d3", "garden-of-life-bone-strength"],
    winner: "citracal-calcium-d3",
    product1Id: "citracal-calcium-d3",
    product2Id: "garden-of-life-bone-strength",
    winnerId: "citracal-calcium-d3",
    winnerReason: "Citracal wins for value, accessibility, and proven calcium citrate absorption.",
    summary: "Citracal wins for value, accessibility, and proven calcium citrate absorption. Garden of Life wins for those who want K2 and a whole-food, organic formula.",
    verdict: "Citracal wins for value, accessibility, and proven calcium citrate absorption. Garden of Life wins for those who want K2 and a whole-food, organic formula.",
    publishDate: "2026-05-02",
  },
  {
    id: "magnesium-vs-melatonin-sleep",
    slug: "magnesium-glycinate-vs-melatonin-sleep",
    title: "Magnesium Glycinate vs. Melatonin for Sleep",
    subtitle: "Root-cause mineral support vs. direct sleep hormone",
    category: "Sleep & Mood Support",
    categorySlug: "sleep-mood-support",
    productIds: ["magnesium-glycinate-sleep", "natrol-melatonin-10mg"],
    winner: "magnesium-glycinate-sleep",
    product1Id: "magnesium-glycinate-sleep",
    product2Id: "natrol-melatonin-10mg",
    winnerId: "magnesium-glycinate-sleep",
    winnerReason: "Magnesium glycinate wins for addressing underlying sleep disruption causes.",
    summary: "Magnesium glycinate wins for addressing underlying sleep disruption causes; melatonin wins for immediate, reliable sleep onset support.",
    verdict: "Magnesium glycinate wins for addressing underlying sleep disruption causes; melatonin wins for immediate, reliable sleep onset support.",
    publishDate: "2026-05-02",
  },
  {
    id: "collagen-vs-b12-cognitive",
    slug: "vital-proteins-collagen-vs-b12-energy",
    title: "Vital Proteins Collagen vs. Jarrow B12 for Energy",
    subtitle: "Structural support vs. metabolic energy",
    category: "Cognitive & Energy Support",
    categorySlug: "cognitive-energy-support",
    productIds: ["vital-proteins-collagen-peptides", "vitamin-b12-energy"],
    winner: "vitamin-b12-energy",
    product1Id: "vitamin-b12-energy",
    product2Id: "vital-proteins-collagen-peptides",
    winnerId: "vitamin-b12-energy",
    winnerReason: "B12 wins for direct energy and cognitive support.",
    summary: "B12 wins for direct energy and cognitive support; collagen wins for skin, joint, and hair benefits with secondary energy support.",
    verdict: "B12 wins for direct energy and cognitive support; collagen wins for skin, joint, and hair benefits with secondary energy support.",
    publishDate: "2026-05-02",
  },
  {
    id: "alpha-gpc-vs-rhodiola-brain-fog",
    slug: "alpha-gpc-vs-rhodiola-brain-fog",
    title: "Alpha GPC vs. Rhodiola Rosea for Brain Fog",
    subtitle: "Targeted neurotransmitter support vs. adaptogenic stress management",
    category: "Cognitive & Energy Support",
    categorySlug: "cognitive-energy-support",
    productIds: ["alpha-gpc-cognitive", "rhodiola-rosea-energy"],
    winner: "alpha-gpc-cognitive",
    product1Id: "alpha-gpc-cognitive",
    product2Id: "rhodiola-rosea-energy",
    winnerId: "alpha-gpc-cognitive",
    winnerReason: "Alpha-GPC wins for direct cognitive support targeting brain fog.",
    summary: "Alpha GPC wins for targeted brain fog relief via acetylcholine support; Rhodiola wins for stress-driven fatigue and mental performance under pressure.",
    verdict: "Alpha GPC wins for targeted brain fog relief via acetylcholine support; Rhodiola wins for stress-driven fatigue and mental performance under pressure.",
    publishDate: "2026-05-02",
  },
];

/** Get a product by its id field (used by ComparisonCard and comparison pages) */
export function getProductById(id: string): Product | undefined {
  return allProducts.find((p) => p.id === id);
}

/** Get comparisons that include a specific category's products */
export function getComparisonsByCategory(categorySlug: string): Comparison[] {
  const categoryProductIds = getProductsByCategory(categorySlug).map((p) => p.id);
  return comparisons.filter((c) =>
    c.productIds.some((id) => categoryProductIds.includes(id))
  );
}

/** Get a comparison by its slug */
export function getComparisonBySlug(slug: string): Comparison | undefined {
  return comparisons.find((c) => c.slug === slug);
}
